### ISSUE TITLE
Not detecting Heroku remotes with https

### ISSUE THREAD

**Issue by calebthompson** [tpope/vim-heroku#3]
Having used the `heroku git:remote --app myapp-staging --remote staging` command to add heroku remotes, I have the following in my $project_root/.git/config:

```
[remote "staging"]
	url = https://git.heroku.com/myapp-staging.git
	fetch = +refs/heads/*:refs/remotes/staging/*
[remote "production"]
	url = https://git.heroku.com/myapp-production.git
	fetch = +refs/heads/*:refs/remotes/production/*
```

These urls are not matched by https://github.com/tpope/vim-heroku/blob/13351fae74cc9e9e86d6421bab8499a1c9359cef/plugin/heroku.vim#L218, which assumes a `:` instead of a `/` before the app name.

This leads to not having :Staging or :Production commands.

Oddly, and this may not be related, I do have a `:Heroku` command that I can't account for outside of this plugin. I don't have a `[remote "heroku"]` and it does not respect Dispatch.vim as `:Hk` does.

**Comment by tpope** [comment]
Tweaked regex would be great.

**Comment by calebthompson** [comment]
#4
