### ISSUE TITLE
:Staging not picked up

### ISSUE THREAD

**Issue by jc00ke** [tpope/vim-heroku#5]
Here's my `.git/config`

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = git@github.com:client/app.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
	rebase = true
[heroku]
	remote = staging
[merge]
	ff = only
```

`E492: Not an editor command: Staging`

**Comment by tpope** [comment]
You don't have a staging remote!

**Comment by jc00ke** [comment]
Maybe `Plus it adds a command wrapper for each Heroku remote in your Git config, so :Staging console is only a few keystrokes away.` can be reworded? That sounds like what I have, but apparently it's not.

**Comment by tpope** [comment]
I genuinely don't understand your confusion so let me just ask how you expect this to work when the name of a Heroku app doesn't even appear in your config? How are you even deploying?

**Comment by jc00ke** [comment]
We deploy with Heroku Pipelines.
When I saw `heroku.remote=staging` in the config above I thought it would get picked up. I read that sentence in the README as "`vim-heroku` wiill pick up the remotes under `[heroku]`" but I clearly read that incorrectly.

**Comment by jc00ke** [comment]
I haven't deployed to Heroku in almost 3 years... clearly I don't have my wits about me with respect to this. Adding the actual remotes worked, and now `:Staging` and `Production` work very nicely.
